In [97]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [98]:
import os

In [99]:
path_proj_datasets = "/content/drive/MyDrive/llm_from_scratch/datasets"

In [100]:
os.chdir(path_proj_datasets)
print(os.getcwd())

/content/drive/MyDrive/llm_from_scratch/datasets

In [101]:
import pandas as pd

In [102]:
df = pd.read_csv("/content/drive/MyDrive/llm_from_scratch/datasets/SMSSpamCollection", sep="\t")

In [103]:
df.head()

,ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."
0,ham,Ok lar... Joking wif u oni...
1,spam,Free entry in 2 a wkly comp to win FA Cup fina...
2,ham,U dun say so early hor... U c already then say...
3,ham,"Nah I don't think he goes to usf, he lives aro..."
4,spam,FreeMsg Hey there darling it's been 3 week's n...

In [104]:
df.head(0)

Empty DataFrame
Columns: [ham, Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...]
Index: []

In [105]:
df.columns = ['l', 't']

In [106]:
df.rename(columns={'l': 'Label', 't': 'Text'}, inplace=True)

In [107]:
df.head()

  Label                                               Text
0   ham                      Ok lar... Joking wif u oni...
1  spam  Free entry in 2 a wkly comp to win FA Cup fina...
2   ham  U dun say so early hor... U c already then say...
3   ham  Nah I don't think he goes to usf, he lives aro...
4  spam  FreeMsg Hey there darling it's been 3 week's n...

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5571 entries, 0 to 5570
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   5571 non-null   object
 1   Text    5571 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [109]:
df.describe()

       Label                    Text
count   5571                    5571
unique     2                    5168
top      ham  Sorry, I'll call later
freq    4824                      30

In [110]:
print((df['Label'] == 'spam').sum())
print((df['Label'] == 'ham').sum())

747
4824

In [111]:
ham_df = df[df['Label'] == 'ham']

In [112]:
len(ham_df)

4824

In [113]:
spam_df = df[df['Label'] == 'spam']
len(spam_df)

747

In [114]:
ham_df = ham_df.head(len(ham_df) - (len(ham_df)-747))
ham_df.head()

  Label                                               Text
0   ham                      Ok lar... Joking wif u oni...
2   ham  U dun say so early hor... U c already then say...
3   ham  Nah I don't think he goes to usf, he lives aro...
5   ham  Even my brother is not like to speak with me. ...
6   ham  As per your request 'Melle Melle (Oru Minnamin...

In [116]:
len(ham_df)

747

In [118]:
spam_df['temp_key'] = range(len(spam_df))
ham_df['temp_key'] = range(len(ham_df))

In [120]:
spam_df['source'] = 'spam'
ham_df['source'] = 'ham'

In [121]:
df = pd.concat([spam_df, ham_df]).sort_values(['temp_key', 'source'])
df.drop(['temp_key', 'source'], axis=1, inplace=True)

In [122]:
df.shape

(1494, 2)

In [127]:
df.head()

  Label                                               Text
0   ham                      Ok lar... Joking wif u oni...
1  spam  Free entry in 2 a wkly comp to win FA Cup fina...
2   ham  U dun say so early hor... U c already then say...
4  spam  FreeMsg Hey there darling it's been 3 week's n...
3   ham  Nah I don't think he goes to usf, he lives aro...

In [131]:
len(df[df['Label'] == 'spam'])

747

In [132]:
len(df[df['Label'] == 'ham'])

747

In [133]:
df['Label'] = df['Label'].map({'spam': 1, 'ham': 0})

In [135]:
df.head()

   Label                                               Text
0      0                      Ok lar... Joking wif u oni...
1      1  Free entry in 2 a wkly comp to win FA Cup fina...
2      0  U dun say so early hor... U c already then say...
4      1  FreeMsg Hey there darling it's been 3 week's n...
3      0  Nah I don't think he goes to usf, he lives aro...